# Generated by Django 3.2.7 on 2021-09-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(default='No Summary Provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
